### ISSUE TITLE
1章で気になった箇所

### ISSUE THREAD

**Issue by uribo** [HOXOMInc/Learning_R_Programming#6]
P.3 `1.2 なぜRが必要か`
> したがって、Rや拡張にパッケージを導入する

Rや拡張パッケージ、の誤植?

P.8 のOSの表記に関して。
`macOS X` だと`macOS` (10.12以降)か`Mac OS X` (10.12以前)を指しているのか混乱するような...。どちらかに合わせて方が適当そう。

ref) https://en.wikipedia.org/wiki/MacOS

P.13のヘルプの呼び出し方。`help()`について言及しない?

**Comment by dichika** [comment]
ありがとうございます。以下は誤植ですね。
・ P3 26L　Rや拡張にパッケージ→Rや拡張パッケージ

・P8 16L macOS X→MacOS X 
ここは校正時に表記修正された箇所でもあるので出版社と検討します。

・P13 こちらは原文では?のみに触れているため、help()の追加については訳注として対応するかどうか検討します。
