### ISSUE TITLE
第6章 で誤植かと思った箇所

### ISSUE THREAD

**Issue by niszet** [HOXOMInc/Learning_R_Programming#7]
五月雨ですみません。追加で2点気づいた点です。

p.169 L20? : readLines() の後の fruits/ が不要？
p.172 L4 : 2つめのgreplも太字にすべき？（こちらは元のままでも良いのかもしれませんが、p248などの式では同一式の同名の関数はすべて太字のため）

**Comment by dichika** [comment]
ありがとうございます。
P169：fruitsオブジェクトの内容を確認しているため、改行してバックスラッシュを削るのが正しいですね。
P172：2つのgreplも太字ですね。修正します。
