### ISSUE TITLE
3章で気になった箇所

### ISSUE THREAD

**Issue by uribo** [HOXOMInc/Learning_R_Programming#8]
2点です。

P. 69 `3.3 グローバルオプションの変更`
`option()` となっているのは `options()` か

P. 77
`install_github("hadley/ggplot2")` は現在リポジトリの所属が変わって `install_github("tidyverse/ggplot2")` となっている（脚注?）

**Comment by dichika** [comment]
ありがとうございます。
P69→options()ですね。
P77→こちらは脚注対応かと思いますが出版社と相談します。
